name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # Call your custom action template
      - name: Run Pbuild Template
        uses: adrianschroeter/pbuild@main
        with:
          dist: 'tumbleweed' # Optional: defaults to tumbleweed anyway

      # Export build artifacts
      - uses: actions/upload-artifact@v7
        with:
          name: tumbleweed-x86_64-logfile
          path: _build.tumbleweed.x86_64/_log
          archive: false
      - uses: actions/upload-artifact@v7
        with:
          name: tumbleweed-x86_64-rpms
          path: _build.tumbleweed.x86_64/bc-1*.x86_64.rpm
          archive: false

